targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      freezed|freezed:
        generate_for:
          include:
            - lib/domain/models/**/*.dart
            - lib/application/providers/**/*.dart
