name: amar_thikana
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  flutter_dotenv: ^5.2.1
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.8.0
  google_maps_flutter: ^2.12.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.1
  sign_in_with_apple: ^7.0.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  dots_indicator: ^3.0.0
  intl: ^0.18.0
  image_picker: ^1.0.4
  firebase_storage: ^12.4.5
  hive: ^2.2.3
  path: ^1.9.1
  logging: ^1.2.0
  dartz: ^0.10.1
  timeago: ^3.7.0
  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1
  logger: ^2.5.0
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  timezone: ^0.10.1
  flutter_local_notifications: ^19.1.0
  uuid: ^4.5.1
  firebase_analytics: ^11.4.5
  flutter_native_timezone: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/
    - assets/images/onboarding/
    - assets/fonts/
    - assets/animations/
    - assets/translations/
    - assets/icons/
